### ISSUE TITLE
Mention TailwindCSS and you get banned

### ISSUE THREAD

**Issue by tdecoy** [yogurt-foundation/yogurt-css#20]
Whatever you do, don't ask what makes YogurtCSS different from TailwindCSS. He'll ban you.

**Comment by loouislow81** [comment]
> Whatever you do, don't ask what makes YogurtCSS different from TailwindCSS. He'll ban you.

TailwindCSS has already known about it. Hater is very welcoming and I will be a very open mind. Thank you for in the middle of nowhere of this message. I'll keep this message here forever. Good day.

**Comment by tdecoy** [comment]
> > Whatever you do, don't ask what makes YogurtCSS different from TailwindCSS. He'll ban you.
> 
> TailwindCSS has already known about it. Hater is very welcoming and I will be a very open mind. Thank you for in the middle of nowhere of this message. I'll keep this message here forever. Have a nice day.

Please do, please keep the message here so others can learn.

And it's NOT "in the middle of nowhere" -- I had simple questions regarding your FW, which I politely asked you. The next thing I know, I'm banned with zero explanation. Very professional, you seem like a fantastic fellow.

**Comment by loouislow81** [comment]
Don't worry I won't fall in your drama script. Have a nice day.

**Comment by tdecoy** [comment]
> Don't worry I won't fall in your drama script. Have a nice day.
Maybe you could explain why I was banned? I'm genuinely curious.

You too, have a nice day 👍
