### ISSUE TITLE
'main' has been outdated in package.json

### ISSUE THREAD

**Issue by SeaniaTwix** [yogurt-foundation/yogurt-css#22]
```ts
import 'yogurt-css' // error 
import 'yogurt-css/dist/yogurt-1.1.2_solidcore.css' // works fine
```

Currently [package.json](https://github.com/yogurt-foundation/yogurt-css/blob/master/package.json#L5) points to version 1.1.1.

I don't know how works in npm and yarn classic both, but it's definitely occurs error on yarn berry.

```
    throw firstError;
    ^

Error: Qualified path resolution failed - none of the candidates can be found on the disk.

Source path: ~/dev/community/.yarn/cache/yogurt-css-npm-1.1.2-716182856b-5cfe1ade22.zip/node_modules/yogurt-css/
Rejected candidate: ~/dev/community/.yarn/cache/yogurt-css-npm-1.1.2-716182856b-5cfe1ade22.zip/node_modules/yogurt-css/
Rejected candidate: ~/dev/community/.yarn/cache/yogurt-css-npm-1.1.2-716182856b-5cfe1ade22.zip/node_modules/yogurt-css/dist/yogurt-1.1.1_solidcore.css

```

**Comment by loouislow81** [comment]
> ```ts
> import 'yogurt-css' // error 
> import 'yogurt-css/dist/yogurt-1.1.2_solidcore.css' // works fine
> ```

Oh, man. This is a very big mistake. 
I have automated to check the version on each build but missed this one.

New v1.1.3 is released soon, maybe next month earlier.

Thanks everything you did for **Yogurt**.
